# Gems for building the InRes docs site.
#
# Build with:  cd docs && bundle install && bundle exec jekyll serve
# The wiki pages must be assembled first: ./scripts/build-docs.sh
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.10.1"

group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

# Not bundled with Ruby 3.4+.
gem "csv"
gem "base64"
gem "bigdecimal"

# Windows / JRuby timezone data.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
